// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5lLvJ1tYofTi6rhfA_RGupWnu2lWmicM',
    appId: '1:102643406767:web:e1408c022941c43f9f015a',
    messagingSenderId: '102643406767',
    projectId: 'mybills-f5d3e',
    authDomain: 'mybills-f5d3e.firebaseapp.com',
    storageBucket: 'mybills-f5d3e.appspot.com',
    measurementId: 'G-H5RCF0VM7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPkgRvrQzOXlL-NNTc_XygIFpAro69BPs',
    appId: '1:102643406767:android:769a694240c221759f015a',
    messagingSenderId: '102643406767',
    projectId: 'mybills-f5d3e',
    storageBucket: 'mybills-f5d3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJQJWRCROa0qLw6UzyFaYt7w2DpEiCgLE',
    appId: '1:102643406767:ios:57dd2362e33196df9f015a',
    messagingSenderId: '102643406767',
    projectId: 'mybills-f5d3e',
    storageBucket: 'mybills-f5d3e.appspot.com',
    iosBundleId: 'com.example.myBills',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJQJWRCROa0qLw6UzyFaYt7w2DpEiCgLE',
    appId: '1:102643406767:ios:57dd2362e33196df9f015a',
    messagingSenderId: '102643406767',
    projectId: 'mybills-f5d3e',
    storageBucket: 'mybills-f5d3e.appspot.com',
    iosBundleId: 'com.example.myBills',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5lLvJ1tYofTi6rhfA_RGupWnu2lWmicM',
    appId: '1:102643406767:web:c38ee05af494a78a9f015a',
    messagingSenderId: '102643406767',
    projectId: 'mybills-f5d3e',
    authDomain: 'mybills-f5d3e.firebaseapp.com',
    storageBucket: 'mybills-f5d3e.appspot.com',
    measurementId: 'G-DNWNY3XKM4',
  );
}
